BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "quotes" (
	"ID"	INTEGER,
	"citation"	TEXT NOT NULL,
	"author"	TEXT NOT NULL,
	"rating"	INTEGER DEFAULT 0,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "prepare_quotes" (
	"ID"	INTEGER,
	"date_offer"	TEXT,
	"citation"	TEXT NOT NULL,
	"author"	TEXT NOT NULL,
	"status"	INTEGER DEFAULT -1,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "logs" (
	"ID"	INTEGER,
	"date_time"	TEXT NOT NULL,
	"nickname"	TEXT NOT NULL,
	"ID_quote"	INTEGER NOT NULL,
	"add_number"	INTEGER NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
COMMIT;
