BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "dialogue_1187604933" (
	"ID"	INTEGER,
	"date_time"	TEXT NOT NULL,
	"type_message"	TEXT NOT NULL,
	"message"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "dialogue_1593918381" (
	"ID"	INTEGER,
	"date_time"	TEXT NOT NULL,
	"type_message"	TEXT NOT NULL,
	"message"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "dialogue_2139168362" (
	"ID"	INTEGER,
	"date_time"	TEXT NOT NULL,
	"type_message"	TEXT NOT NULL,
	"message"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "dialogue_5883667925" (
	"ID"	INTEGER,
	"date_time"	TEXT NOT NULL,
	"type_message"	TEXT NOT NULL,
	"message"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "dialogue_5972956918" (
	"ID"	INTEGER,
	"date_time"	TEXT NOT NULL,
	"type_message"	TEXT NOT NULL,
	"message"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "dialogue_7330421128" (
	"ID"	INTEGER,
	"date_time"	TEXT NOT NULL,
	"type_message"	TEXT NOT NULL,
	"message"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "dialogue_7807827990" (
	"ID"	INTEGER,
	"date_time"	TEXT NOT NULL,
	"type_message"	TEXT NOT NULL,
	"message"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "dialogue_8454478180" (
	"ID"	INTEGER,
	"date_time"	TEXT NOT NULL,
	"type_message"	TEXT NOT NULL,
	"message"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "users" (
	"tg_id"	INTEGER,
	"full_name"	TEXT,
	"tg_username"	TEXT NOT NULL,
	"server_nick"	TEXT,
	"rank"	INTEGER DEFAULT 0,
	PRIMARY KEY("tg_id")
);
COMMIT;
